import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from "next/font/google";
import "./globals.css";
import BootsrapClient from '@/components/bootsrapClient';
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header phone={"+91 894 3319 888"} email={"gamcakerala@gmail.com"}/>
        {children}

        <Footer/>
        <BootsrapClient/>
      </body>
    </html>
  );
}
